/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Playlists */
        get: operations["list_playlists_api_playlists_get"];
        put?: never;
        /** Connect */
        post: operations["connect_api_playlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{spotify_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Now */
        post: operations["sync_now_api_playlists__spotify_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{spotify_id}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect */
        post: operations["disconnect_api_playlists__spotify_id__disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{spotify_id}/external-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update External Config
         * @description Per-playlist toggles for §55's "Generate Plex Playlist"/"Generate
         *     Jellyfin Playlist" switches, plus §58's per-platform destination-name
         *     overrides. Server-level enable/credentials live in Settings
         *     (app/api/settings.py) — a playlist can only actually sync once both the
         *     server-level and this per-playlist switch are on.
         */
        put: operations["update_external_config_api_playlists__spotify_id__external_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{spotify_id}/external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get External Status */
        get: operations["get_external_status_api_playlists__spotify_id__external_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{spotify_id}/sync-external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync External
         * @description Manually (re)build this playlist's Jellyfin/Plex playlist right now,
         *     without waiting for the next acquisition/Spotify-resync trigger.
         */
        post: operations["sync_external_api_playlists__spotify_id__sync_external_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{spotify_id}/external/{platform}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Collision
         * @description Resolve a NEEDS_RESOLUTION collision (§59): a same-named,
         *     Groovarr-unmanaged playlist already exists on the target server.
         *     "adopt" takes ownership of it (its contents are rebuilt to match Spotify
         *     on the next sync); "cancel" forgets the conflict so a different name
         *     (set via /external-config) can be tried on the next sync.
         */
        post: operations["resolve_collision_api_playlists__spotify_id__external__platform__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Library Scan */
        post: operations["trigger_library_scan_api_media_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Media Assets */
        get: operations["list_media_assets_api_media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{asset_id}/organize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Organize */
        post: operations["organize_api_media__asset_id__organize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/wanted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wanted Tracks */
        get: operations["wanted_tracks_api_search_wanted_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run All */
        post: operations["run_all_api_search_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/tracks/{track_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run One */
        post: operations["run_one_api_search_tracks__track_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/tracks/{track_id}/search-again": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Again */
        post: operations["search_again_api_search_tracks__track_id__search_again_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/tracks/{track_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidates For Track */
        get: operations["candidates_for_track_api_search_tracks__track_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/tracks/{track_id}/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Candidate Endpoint */
        post: operations["select_candidate_endpoint_api_search_tracks__track_id__select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/tracks/{track_id}/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace Media Endpoint
         * @description §34: replace an already-downloaded track's file with a different
         *     chosen candidate. Unlike `/select` (which only applies to a track with
         *     no file yet), this safely swaps a *working* file: the old one keeps
         *     serving until the new one is fully downloaded, validated, and imported
         *     (see app.services.replacement for the exact sequence and why a plain
         *     Manual Selection can't be reused for this case).
         */
        post: operations["replace_media_endpoint_api_search_tracks__track_id__replace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Queue */
        get: operations["list_queue_api_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{asset_id}/enqueue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue */
        post: operations["enqueue_api_queue__asset_id__enqueue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{asset_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_queue__asset_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{asset_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_queue__asset_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/sync-interval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Sync Interval */
        put: operations["update_sync_interval_api_settings_sync_interval_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/spotify-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Spotify Credentials */
        put: operations["update_spotify_credentials_api_settings_spotify_credentials_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/spotify-user-oauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Spotify User Oauth */
        put: operations["update_spotify_user_oauth_api_settings_spotify_user_oauth_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/jellyfin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Jellyfin Config */
        put: operations["update_jellyfin_config_api_settings_jellyfin_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/plex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Plex Config */
        put: operations["update_plex_config_api_settings_plex_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/monitor-better-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Monitor Better Versions
         * @description §36: enabling this may replace an existing music video with a
         *     *different* video, not merely a higher-resolution copy — see
         *     `SettingsOut.monitor_better_versions_warning`, always present in every
         *     response from this router regardless of the toggle's value.
         */
        put: operations["update_monitor_better_versions_api_settings_monitor_better_versions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/matching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Matching Settings */
        put: operations["update_matching_settings_api_settings_matching_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Download Settings */
        put: operations["update_download_settings_api_settings_download_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Lyrics Settings */
        put: operations["update_lyrics_settings_api_settings_lyrics_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Media Settings */
        put: operations["update_media_settings_api_settings_media_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/hardware-acceleration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Hardware Acceleration */
        put: operations["update_hardware_acceleration_api_settings_hardware_acceleration_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spotify/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authorize */
        get: operations["authorize_api_spotify_oauth_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spotify/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spotify Oauth Callback */
        get: operations["spotify_oauth_callback_api_spotify_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lyrics/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lyrics For Track */
        get: operations["get_lyrics_for_track_api_lyrics__track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jellyfin/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Jellyfin Connection */
        post: operations["test_jellyfin_connection_api_jellyfin_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jellyfin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jellyfin Users
         * @description Populates the "Jellyfin user" picker in Settings — required for
         *     playlist mutations (§2 row F). Only needs url + api key to be configured,
         *     not a user id yet (that's what this endpoint is for).
         */
        get: operations["list_jellyfin_users_api_jellyfin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plex/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Plex Connection */
        post: operations["test_plex_connection_api_plex_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plex/library-sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plex Library Sections */
        get: operations["list_plex_library_sections_api_plex_library_sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List History */
        get: operations["list_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Summary */
        get: operations["get_dashboard_summary_api_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/hardware-acceleration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Hardware Acceleration Status */
        get: operations["read_hardware_acceleration_status_api_system_hardware_acceleration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness/readiness probe. Actually checks DB connectivity rather than
         *     hardcoding "ok" — a `db: error` response with an otherwise-200 status
         *     lets callers distinguish "process is up" from "process is fully healthy".
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttemptStatus
         * @enum {string}
         */
        AttemptStatus: "running" | "succeeded" | "failed";
        /** ConnectPlaylistRequest */
        ConnectPlaylistRequest: {
            /** Url Or Id */
            url_or_id: string;
        };
        /**
         * ContainerPolicy
         * @description Controls what `app/integrations/acquisition/ffmpeg_mux.py` does when
         *     the source video/audio codec pair isn't natively MP4-compatible (a
         *     stream-copy into MP4 is always tried first regardless of this setting —
         *     it only affects what happens when that's not possible). See §2 row D of
         *     the architecture doc for the full research tradeoff this encodes.
         * @enum {string}
         */
        ContainerPolicy: "always_mp4" | "prefer_mp4_allow_mkv";
        /** DashboardSummary */
        DashboardSummary: {
            /** Connected Playlists */
            connected_playlists: number;
            /** Finalized Playlists */
            finalized_playlists: number;
            /** Monitored Tracks */
            monitored_tracks: number;
            /** Media By State */
            media_by_state: {
                [key: string]: number;
            };
            /** Active Queue Count */
            active_queue_count: number;
            /** Download Failed Count */
            download_failed_count: number;
            /** Manual Review Required Count */
            manual_review_required_count: number;
            /** Pending Jellyfin Sync */
            pending_jellyfin_sync: number;
            /** Pending Plex Sync */
            pending_plex_sync: number;
            /** Last Spotify Sync At */
            last_spotify_sync_at: string | null;
            /** Next Spotify Sync At */
            next_spotify_sync_at: string | null;
        };
        /** DownloadAttemptOut */
        DownloadAttemptOut: {
            /** Id */
            id: number;
            /** Attempt Number */
            attempt_number: number;
            status: components["schemas"]["AttemptStatus"];
            /** Error Class */
            error_class: string | null;
            /** Error Message */
            error_message: string | null;
            /** Next Retry At */
            next_retry_at: string | null;
        };
        /** DownloadSettingsRequest */
        DownloadSettingsRequest: {
            /** Max Concurrent Downloads */
            max_concurrent_downloads: number;
            /** Max Download Attempts */
            max_download_attempts: number;
        };
        /**
         * ExternalPlatform
         * @enum {string}
         */
        ExternalPlatform: "jellyfin" | "plex";
        /** ExternalPlaylistConfigRequest */
        ExternalPlaylistConfigRequest: {
            /** Jellyfin Enabled */
            jellyfin_enabled?: boolean | null;
            /** Jellyfin Name Override */
            jellyfin_name_override?: string | null;
            /** Plex Enabled */
            plex_enabled?: boolean | null;
            /** Plex Name Override */
            plex_name_override?: string | null;
        };
        /** ExternalPlaylistOut */
        ExternalPlaylistOut: {
            platform: components["schemas"]["ExternalPlatform"];
            /** External Id */
            external_id: string | null;
            sync_state: components["schemas"]["ExternalPlaylistSyncState"];
            /** Sync Error */
            sync_error: string | null;
            /** Duplicates Collapsed Count */
            duplicates_collapsed_count: number | null;
        };
        /**
         * ExternalPlaylistSyncState
         * @enum {string}
         */
        ExternalPlaylistSyncState: "pending" | "synced" | "failed" | "needs_resolution";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HardwareAccelPolicy
         * @description Which encoder `ffmpeg_mux.py` tries for a transcode that's actually
         *     needed (only relevant under `ContainerPolicy.ALWAYS_MP4` — the MKV
         *     fallback path never transcodes at all). See
         *     `app/integrations/acquisition/hwaccel.py` for how availability is
         *     detected.
         * @enum {string}
         */
        HardwareAccelPolicy: "auto" | "disabled" | "nvenc" | "qsv" | "vaapi";
        /** HardwareAccelRequest */
        HardwareAccelRequest: {
            hardware_acceleration: components["schemas"]["HardwareAccelPolicy"];
        };
        /** HardwareAccelStatusOut */
        HardwareAccelStatusOut: {
            /** Nvenc Available */
            nvenc_available: boolean;
            /** Qsv Available */
            qsv_available: boolean;
            /** Vaapi Available */
            vaapi_available: boolean;
            /** Best */
            best: string | null;
        };
        /** HistoryEventOut */
        HistoryEventOut: {
            /** Id */
            id: number;
            /** Track Id */
            track_id: number | null;
            /** Media Asset Id */
            media_asset_id: number | null;
            /** Event Type */
            event_type: string;
            /** Detail */
            detail: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** JellyfinConfigRequest */
        JellyfinConfigRequest: {
            /** Enabled */
            enabled: boolean;
            /** Url */
            url?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Library Id */
            library_id?: string | null;
            /** Media Path */
            media_path?: string | null;
        };
        /** JellyfinUserOut */
        JellyfinUserOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** LibraryScanResultOut */
        LibraryScanResultOut: {
            /** Files Scanned */
            files_scanned: number;
            /** Matched Available */
            matched_available: number;
            /** Manual Review Created */
            manual_review_created: number;
            /** Skipped No Signal */
            skipped_no_signal: number;
            /** Skipped Already Known */
            skipped_already_known: number;
            /** Errors */
            errors: string[];
        };
        /**
         * LyricsKind
         * @enum {string}
         */
        LyricsKind: "synced" | "plain" | "missing";
        /** LyricsOut */
        LyricsOut: {
            /** Track Id */
            track_id: number;
            /** Provider */
            provider: string;
            kind: components["schemas"]["LyricsKind"];
            /** Content */
            content: string | null;
            /** Sidecar Path */
            sidecar_path: string | null;
        };
        /** LyricsSettingsRequest */
        LyricsSettingsRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /** MatchingThresholdRequest */
        MatchingThresholdRequest: {
            /** Automatic Match Threshold */
            automatic_match_threshold: number;
        };
        /** MediaAssetOut */
        MediaAssetOut: {
            /** Id */
            id: number;
            /** Track Id */
            track_id: number | null;
            /** Candidate Track Id */
            candidate_track_id: number | null;
            /** Local Path */
            local_path: string | null;
            /** Container */
            container: string | null;
            /** Resolution Label */
            resolution_label: string | null;
            /** Duration S */
            duration_s: number | null;
            /** File Size */
            file_size: number | null;
            state: components["schemas"]["MediaState"];
            /** Manual Selection */
            manual_selection: boolean;
            /** Review Reason */
            review_reason: string | null;
            /** Source Reference */
            source_reference: string | null;
            jellyfin_sync_status: components["schemas"]["SyncStatus"];
            plex_sync_status: components["schemas"]["SyncStatus"];
            /** Video Candidate Id */
            video_candidate_id: number | null;
            /** Track Artist */
            track_artist: string | null;
            /** Track Title */
            track_title: string | null;
            /** Track Release Year */
            track_release_year: number | null;
            /** Needs Organize */
            needs_organize: boolean;
        };
        /** MediaSettingsRequest */
        MediaSettingsRequest: {
            container_policy: components["schemas"]["ContainerPolicy"];
        };
        /**
         * MediaState
         * @description A media asset's own lifecycle — never mutated by external-server sync
         *     outcomes (those live in `jellyfin_sync_status`/`plex_sync_status`
         *     instead). Deliberately explicit rather than a single boolean (§74).
         * @enum {string}
         */
        MediaState: "wanted" | "searching" | "manual_review_required" | "candidate_selected" | "queued" | "downloading" | "processing" | "importing" | "available" | "incomplete" | "download_failed" | "missing";
        /** MonitorBetterVersionsRequest */
        MonitorBetterVersionsRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /** PlaylistOut */
        PlaylistOut: {
            /** Spotify Id */
            spotify_id: string;
            /** Name */
            name: string;
            /** Connected */
            connected: boolean;
            /** Finalized */
            finalized: boolean;
            /** Sync Interval Hours */
            sync_interval_hours: number;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Next Sync At */
            next_sync_at: string | null;
            /** Track Count */
            track_count: number;
            /** Jellyfin Enabled */
            jellyfin_enabled: boolean;
            /** Jellyfin Name Override */
            jellyfin_name_override: string | null;
            /** Plex Enabled */
            plex_enabled: boolean;
            /** Plex Name Override */
            plex_name_override: string | null;
        };
        /** PlexConfigRequest */
        PlexConfigRequest: {
            /** Enabled */
            enabled: boolean;
            /** Url */
            url?: string | null;
            /** Token */
            token?: string | null;
            /** Library Section Id */
            library_section_id?: string | null;
            /** Media Path */
            media_path?: string | null;
        };
        /** PlexLibrarySectionOut */
        PlexLibrarySectionOut: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** QueueItemOut */
        QueueItemOut: {
            /** Media Asset Id */
            media_asset_id: number;
            /** Track Id */
            track_id: number | null;
            state: components["schemas"]["MediaState"];
            /** Attempts */
            attempts: components["schemas"]["DownloadAttemptOut"][];
        };
        /** ResolveCollisionRequest */
        ResolveCollisionRequest: {
            /** Action */
            action: string;
        };
        /** SearchOutcomeOut */
        SearchOutcomeOut: {
            /** Track Id */
            track_id: number;
            media_state: components["schemas"]["MediaState"];
            /** Manual Selection */
            manual_selection: boolean;
            /** Candidates Found */
            candidates_found: number;
            /** Winning Candidate Id */
            winning_candidate_id: number | null;
        };
        /** SelectCandidateRequest */
        SelectCandidateRequest: {
            /** Video Candidate Id */
            video_candidate_id: number;
        };
        /** SettingsOut */
        SettingsOut: {
            /** Default Sync Interval Hours */
            default_sync_interval_hours: number;
            /** Spotify Client Id */
            spotify_client_id: string | null;
            /** Spotify Client Configured */
            spotify_client_configured: boolean;
            /** Spotify User Oauth Enabled */
            spotify_user_oauth_enabled: boolean;
            /** Spotify Needs Reauth */
            spotify_needs_reauth: boolean;
            /** Jellyfin Enabled */
            jellyfin_enabled: boolean;
            /** Jellyfin Url */
            jellyfin_url: string | null;
            /** Jellyfin Configured */
            jellyfin_configured: boolean;
            /** Jellyfin User Id */
            jellyfin_user_id: string | null;
            /** Jellyfin Library Id */
            jellyfin_library_id: string | null;
            /** Jellyfin Media Path */
            jellyfin_media_path: string | null;
            /** Plex Enabled */
            plex_enabled: boolean;
            /** Plex Url */
            plex_url: string | null;
            /** Plex Configured */
            plex_configured: boolean;
            /** Plex Library Section Id */
            plex_library_section_id: string | null;
            /** Plex Media Path */
            plex_media_path: string | null;
            /** Monitor Better Versions Enabled */
            monitor_better_versions_enabled: boolean;
            /** Monitor Better Versions Warning */
            monitor_better_versions_warning: string;
            /** Automatic Match Threshold */
            automatic_match_threshold: number;
            /** Max Concurrent Downloads */
            max_concurrent_downloads: number;
            /** Max Download Attempts */
            max_download_attempts: number;
            /** Lyrics Enabled */
            lyrics_enabled: boolean;
            container_policy: components["schemas"]["ContainerPolicy"];
            hardware_acceleration: components["schemas"]["HardwareAccelPolicy"];
        };
        /** SpotifyCredentialsRequest */
        SpotifyCredentialsRequest: {
            /** Client Id */
            client_id: string;
            /** Client Secret */
            client_secret: string;
        };
        /** SpotifyUserOAuthToggleRequest */
        SpotifyUserOAuthToggleRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * SyncStatus
         * @description External media-server sync status — orthogonal to `MediaState` (§61).
         *     Used identically for both `jellyfin_sync_status` and `plex_sync_status`.
         * @enum {string}
         */
        SyncStatus: "not_configured" | "pending_sync" | "synced" | "failed_sync";
        /** UpdateSyncIntervalRequest */
        UpdateSyncIntervalRequest: {
            /** Default Sync Interval Hours */
            default_sync_interval_hours: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoCandidateOut */
        VideoCandidateOut: {
            /** Id */
            id: number;
            /** Youtube Video Id */
            youtube_video_id: string;
            /** Title */
            title: string;
            /** Channel Id */
            channel_id: string | null;
            /** Channel Name */
            channel_name: string | null;
            /** Duration S */
            duration_s: number | null;
            /** Orientation */
            orientation: string;
            /** Official Signals */
            official_signals: {
                [key: string]: unknown;
            };
            /** Score */
            score: number;
            /** Score Breakdown */
            score_breakdown: unknown[];
            /** Rejection Flags */
            rejection_flags: unknown[];
        };
        /** WantedTrackOut */
        WantedTrackOut: {
            /** Id */
            id: number;
            /** Canonical Artist */
            canonical_artist: string;
            /** Featured Artists */
            featured_artists: string[];
            /** Canonical Title */
            canonical_title: string;
            /** Parsed Version */
            parsed_version: string | null;
            /** Duration Ms */
            duration_ms: number;
            /** Explicit */
            explicit: boolean;
            /** Playlist Names */
            playlist_names: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_playlists_api_playlists_get: {
        parameters: {
            query?: {
                /** @description Max rows to return. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_api_playlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectPlaylistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_now_api_playlists__spotify_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotify_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_api_playlists__spotify_id__disconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotify_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_external_config_api_playlists__spotify_id__external_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotify_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalPlaylistConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_external_status_api_playlists__spotify_id__external_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotify_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalPlaylistOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_external_api_playlists__spotify_id__sync_external_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotify_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalPlaylistOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_collision_api_playlists__spotify_id__external__platform__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotify_id: string;
                platform: components["schemas"]["ExternalPlatform"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveCollisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalPlaylistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_library_scan_api_media_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryScanResultOut"];
                };
            };
        };
    };
    list_media_assets_api_media_get: {
        parameters: {
            query?: {
                state?: components["schemas"]["MediaState"] | null;
                for_track?: number | null;
                /** @description Max rows to return. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    organize_api_media__asset_id__organize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wanted_tracks_api_search_wanted_get: {
        parameters: {
            query?: {
                /** @description Max rows to return. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WantedTrackOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_all_api_search_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOutcomeOut"][];
                };
            };
        };
    };
    run_one_api_search_tracks__track_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOutcomeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_again_api_search_tracks__track_id__search_again_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOutcomeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidates_for_track_api_search_tracks__track_id__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoCandidateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_candidate_endpoint_api_search_tracks__track_id__select_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectCandidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOutcomeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_media_endpoint_api_search_tracks__track_id__replace_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectCandidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOutcomeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_queue_api_queue_get: {
        parameters: {
            query?: {
                /** @description Max rows to return. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_api_queue__asset_id__enqueue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_queue__asset_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_queue__asset_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_sync_interval_api_settings_sync_interval_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSyncIntervalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_spotify_credentials_api_settings_spotify_credentials_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpotifyCredentialsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_spotify_user_oauth_api_settings_spotify_user_oauth_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpotifyUserOAuthToggleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_jellyfin_config_api_settings_jellyfin_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JellyfinConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plex_config_api_settings_plex_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlexConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_monitor_better_versions_api_settings_monitor_better_versions_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorBetterVersionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_matching_settings_api_settings_matching_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchingThresholdRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_download_settings_api_settings_download_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lyrics_settings_api_settings_lyrics_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LyricsSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_media_settings_api_settings_media_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_hardware_acceleration_api_settings_hardware_acceleration_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HardwareAccelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_api_spotify_oauth_authorize_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    spotify_oauth_callback_api_spotify_oauth_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lyrics_for_track_api_lyrics__track_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LyricsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_jellyfin_connection_api_jellyfin_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_jellyfin_users_api_jellyfin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JellyfinUserOut"][];
                };
            };
        };
    };
    test_plex_connection_api_plex_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_plex_library_sections_api_plex_library_sections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlexLibrarySectionOut"][];
                };
            };
        };
    };
    list_history_api_history_get: {
        parameters: {
            query?: {
                track_id?: number | null;
                media_asset_id?: number | null;
                /** @description Max rows to return. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_summary_api_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    read_hardware_acceleration_status_api_system_hardware_acceleration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareAccelStatusOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
