"""history_events_and_performance_indexes

Revision ID: 0269e6ae5d04
Revises: ba104197602a
Create Date: 2026-09-14 11:43:20.073678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0269e6ae5d04'
down_revision: Union[str, Sequence[str], None] = 'ba104197602a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('media_asset_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_events_media_asset_id'), ['media_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_events_track_id'), ['track_id'], unique=False)

    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_state'), ['state'], unique=False)

    with op.batch_alter_table('playlist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_entries_playlist_id'), ['playlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_entries_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_entries_track_id'))
        batch_op.drop_index(batch_op.f('ix_playlist_entries_playlist_id'))

    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_state'))

    with op.batch_alter_table('history_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_events_track_id'))
        batch_op.drop_index(batch_op.f('ix_history_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_history_events_media_asset_id'))
        batch_op.drop_index(batch_op.f('ix_history_events_event_type'))

    op.drop_table('history_events')
    # ### end Alembic commands ###
