"""lyrics

Revision ID: 0bb742def944
Revises: 876e339638dc
Create Date: 2026-09-14 10:32:23.706187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb742def944'
down_revision: Union[str, Sequence[str], None] = '876e339638dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lyrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('SYNCED', 'PLAIN', 'MISSING', name='lyricskind', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sidecar_path', sa.String(length=2048), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('negative_cache_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lyrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lyrics_track_id'), ['track_id'], unique=True)

    # `server_default` is required here (not just an ORM-level default):
    # existing rows created before this migration must get a concrete value
    # for a new NOT NULL column, not just future inserts (same pattern as
    # 876e339638dc's tags_written column). Dropped again afterward since the
    # ORM model's own `default=True` covers all new rows going forward.
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lyrics_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('lyrics_enabled', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('lyrics_enabled')

    with op.batch_alter_table('lyrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lyrics_track_id'))

    op.drop_table('lyrics')
    # ### end Alembic commands ###
