"""media assets and playlist media references

Revision ID: 21fc715438e7
Revises: b9bcd983152c
Create Date: 2026-09-14 09:40:54.009093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fc715438e7'
down_revision: Union[str, Sequence[str], None] = 'b9bcd983152c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('local_path', sa.String(length=2048), nullable=True),
    sa.Column('container', sa.String(length=32), nullable=True),
    sa.Column('video_codec', sa.String(length=64), nullable=True),
    sa.Column('audio_codec', sa.String(length=64), nullable=True),
    sa.Column('resolution_label', sa.String(length=16), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.Enum('WANTED', 'SEARCHING', 'MANUAL_REVIEW_REQUIRED', 'CANDIDATE_SELECTED', 'QUEUED', 'DOWNLOADING', 'PROCESSING', 'IMPORTING', 'AVAILABLE', 'INCOMPLETE', 'DOWNLOAD_FAILED', 'MISSING', name='mediastate', native_enum=False, length=32), nullable=False),
    sa.Column('manual_selection', sa.Boolean(), nullable=False),
    sa.Column('jellyfin_sync_status', sa.Enum('NOT_CONFIGURED', 'PENDING_SYNC', 'SYNCED', 'FAILED_SYNC', name='syncstatus', native_enum=False, length=32), nullable=False),
    sa.Column('plex_sync_status', sa.Enum('NOT_CONFIGURED', 'PENDING_SYNC', 'SYNCED', 'FAILED_SYNC', name='syncstatus', native_enum=False, length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=512), nullable=True),
    sa.Column('candidate_track_id', sa.Integer(), nullable=True),
    sa.Column('review_reason', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['candidate_track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_track_id'), 'media_assets', ['track_id'], unique=False)
    op.create_table('playlist_media_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['spotify_playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'track_id', 'media_asset_id', name='uq_playlist_track_media')
    )
    op.create_index(op.f('ix_playlist_media_references_media_asset_id'), 'playlist_media_references', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_playlist_media_references_playlist_id'), 'playlist_media_references', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_media_references_track_id'), 'playlist_media_references', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_media_references_track_id'), table_name='playlist_media_references')
    op.drop_index(op.f('ix_playlist_media_references_playlist_id'), table_name='playlist_media_references')
    op.drop_index(op.f('ix_playlist_media_references_media_asset_id'), table_name='playlist_media_references')
    op.drop_table('playlist_media_references')
    op.drop_index(op.f('ix_media_assets_track_id'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
