"""hardware_acceleration_setting

Revision ID: 63daa53d45e8
Revises: 9503776b8b06
Create Date: 2026-09-14 18:40:29.761596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63daa53d45e8'
down_revision: Union[str, Sequence[str], None] = '9503776b8b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='auto' so an existing settings row is backfilled
    # cleanly (SQLite's batch-mode table rebuild needs a value for the new
    # NOT NULL column on any pre-existing row) — 'auto' is the enum's own
    # .value (not its NAME), matching the values_callable mapping the model
    # column uses, per the container_policy KeyError bug fixed earlier.
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'hardware_acceleration',
                sa.Enum('auto', 'disabled', 'nvenc', 'qsv', 'vaapi', name='hardwareaccelpolicy', native_enum=False, length=16),
                nullable=False,
                server_default='auto',
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('hardware_acceleration')

    # ### end Alembic commands ###
