"""external_playlists_and_media_server_settings

Revision ID: 77c72dae5f33
Revises: 0bb742def944
Create Date: 2026-09-14 10:52:16.137512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c72dae5f33'
down_revision: Union[str, Sequence[str], None] = '0bb742def944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('JELLYFIN', 'PLEX', name='externalplatform', native_enum=False, length=16), nullable=False),
    sa.Column('spotify_playlist_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('last_synced_name', sa.String(length=512), nullable=True),
    sa.Column('adopted', sa.Boolean(), nullable=False),
    sa.Column('sync_state', sa.Enum('PENDING', 'SYNCED', 'FAILED', 'NEEDS_RESOLUTION', name='externalplaylistsyncstate', native_enum=False, length=32), nullable=False),
    sa.Column('sync_error', sa.String(length=1024), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_snapshot', sa.String(length=128), nullable=True),
    sa.Column('duplicates_collapsed_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spotify_playlist_id'], ['spotify_playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'spotify_playlist_id', name='uq_external_playlist_platform_spotify_playlist')
    )
    with op.batch_alter_table('external_playlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_playlists_spotify_playlist_id'), ['spotify_playlist_id'], unique=False)

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jellyfin_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('jellyfin_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('jellyfin_api_key_encrypted', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('jellyfin_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('jellyfin_library_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('plex_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('plex_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('plex_token_encrypted', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('plex_library_section_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('plex_media_path', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('plex_media_path')
        batch_op.drop_column('plex_library_section_id')
        batch_op.drop_column('plex_token_encrypted')
        batch_op.drop_column('plex_url')
        batch_op.drop_column('plex_enabled')
        batch_op.drop_column('jellyfin_library_id')
        batch_op.drop_column('jellyfin_user_id')
        batch_op.drop_column('jellyfin_api_key_encrypted')
        batch_op.drop_column('jellyfin_url')
        batch_op.drop_column('jellyfin_enabled')

    with op.batch_alter_table('external_playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_playlists_spotify_playlist_id'))

    op.drop_table('external_playlists')
    # ### end Alembic commands ###
