"""media assets tags_written column

Revision ID: 876e339638dc
Revises: 8e89cacedbbf
Create Date: 2026-09-14 10:23:06.222817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876e339638dc'
down_revision: Union[str, Sequence[str], None] = '8e89cacedbbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # `server_default` is required here (not just an ORM-level default):
    # existing rows created before this migration must get a concrete value
    # for a new NOT NULL column, not just future inserts. Dropped again
    # afterward since the ORM model's own `default=False` covers all new
    # rows going forward — the column doesn't need a permanent DB-level
    # default.
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('tags_written', sa.Boolean(), nullable=False, server_default=sa.false())
        )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.alter_column('tags_written', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_column('tags_written')

    # ### end Alembic commands ###
