"""media_assets_pending_reference_swap

Revision ID: 8bb8b7ff0aa5
Revises: 0269e6ae5d04
Create Date: 2026-09-14 11:45:29.497453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb8b7ff0aa5'
down_revision: Union[str, Sequence[str], None] = '0269e6ae5d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # `server_default` required for existing rows (same pattern as
    # 876e339638dc's `tags_written` column) — every pre-existing MediaAsset
    # is, by definition, not a mid-flight replacement attempt, so `false` is
    # the correct value for all of them. Dropped again afterward since the
    # ORM model's `default=False` covers all new rows going forward.
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('pending_reference_swap', sa.Boolean(), nullable=False, server_default=sa.false())
        )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.alter_column('pending_reference_swap', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_column('pending_reference_swap')

    # ### end Alembic commands ###
