"""download attempts and queue settings

Revision ID: 8e89cacedbbf
Revises: cc880284ef2a
Create Date: 2026-09-14 10:15:44.563668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e89cacedbbf'
down_revision: Union[str, Sequence[str], None] = 'cc880284ef2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', name='attemptstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_class', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_attempts_media_asset_id'), ['media_asset_id'], unique=False)

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_concurrent_downloads', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_download_attempts', sa.Integer(), nullable=False))

    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_is_visualizer_only', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('retry_requested_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_column('retry_requested_at')
        batch_op.drop_column('candidate_is_visualizer_only')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('max_download_attempts')
        batch_op.drop_column('max_concurrent_downloads')

    with op.batch_alter_table('download_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_attempts_media_asset_id'))

    op.drop_table('download_attempts')
    # ### end Alembic commands ###
