"""jellyfin media path remap

Revision ID: a0581ca1e2f4
Revises: 77c72dae5f33
Create Date: 2026-09-14 11:01:53.007669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0581ca1e2f4'
down_revision: Union[str, Sequence[str], None] = '77c72dae5f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jellyfin_media_path', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('jellyfin_media_path')

    # ### end Alembic commands ###
