"""spotify playlists, tracks, entries, app settings

Revision ID: b9bcd983152c
Revises: 81e005d510b8
Create Date: 2026-09-14 09:31:09.565384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bcd983152c'
down_revision: Union[str, Sequence[str], None] = '81e005d510b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_sync_interval_hours', sa.Integer(), nullable=False),
    sa.Column('spotify_client_id', sa.String(length=256), nullable=True),
    sa.Column('spotify_client_secret_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('spotify_user_oauth_enabled', sa.Boolean(), nullable=False),
    sa.Column('spotify_refresh_token_encrypted', sa.String(length=2048), nullable=True),
    sa.Column('spotify_refresh_token_obtained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spotify_needs_reauth', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spotify_playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('snapshot_id', sa.String(length=128), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_hours', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plex_enabled', sa.Boolean(), nullable=False),
    sa.Column('jellyfin_enabled', sa.Boolean(), nullable=False),
    sa.Column('plex_name_override', sa.String(length=512), nullable=True),
    sa.Column('jellyfin_name_override', sa.String(length=512), nullable=True),
    sa.Column('artwork_path', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spotify_playlists_spotify_id'), 'spotify_playlists', ['spotify_id'], unique=True)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_artist', sa.String(length=512), nullable=False),
    sa.Column('featured_artists', sa.JSON(), nullable=False),
    sa.Column('canonical_title', sa.String(length=512), nullable=False),
    sa.Column('parsed_version', sa.String(length=256), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('explicit', sa.Boolean(), nullable=False),
    sa.Column('album_artwork_path', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_spotify_track_id'), 'tracks', ['spotify_track_id'], unique=True)
    op.create_table('playlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('occurrence_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['spotify_playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'track_id', 'occurrence_index', name='uq_playlist_track_occurrence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_entries')
    op.drop_index(op.f('ix_tracks_spotify_track_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_spotify_playlists_spotify_id'), table_name='spotify_playlists')
    op.drop_table('spotify_playlists')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
