"""monitor better versions setting

Revision ID: ba104197602a
Revises: a0581ca1e2f4
Create Date: 2026-09-14 11:26:37.564505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba104197602a'
down_revision: Union[str, Sequence[str], None] = 'a0581ca1e2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # `server_default` is required (not just an ORM-level default): the
    # `app_settings` singleton row almost always already exists by the time
    # this migration runs, so a new NOT NULL column needs a concrete value
    # for that existing row, not just future inserts. Dropped again
    # afterward since the ORM model's own `default=False` covers all new
    # rows going forward.
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('monitor_better_versions_enabled', sa.Boolean(), nullable=False, server_default=sa.false())
        )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('monitor_better_versions_enabled', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('monitor_better_versions_enabled')

    # ### end Alembic commands ###
