"""video candidates and automatic match threshold

Revision ID: cc880284ef2a
Revises: 21fc715438e7
Create Date: 2026-09-14 09:57:31.641254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc880284ef2a'
down_revision: Union[str, Sequence[str], None] = '21fc715438e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('channel_name', sa.String(length=512), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('orientation', sa.String(length=16), nullable=False),
    sa.Column('official_signals', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('rejection_flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_candidates_track_id'), ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_candidates_youtube_video_id'), ['youtube_video_id'], unique=False)

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'automatic_match_threshold',
                sa.Integer(),
                nullable=False,
                server_default='70',
            )
        )

    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_candidate_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_media_assets_video_candidate_id'), ['video_candidate_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_media_assets_video_candidate_id_video_candidates', 'video_candidates', ['video_candidate_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_media_assets_video_candidate_id_video_candidates', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_media_assets_video_candidate_id'))
        batch_op.drop_column('video_candidate_id')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('automatic_match_threshold')

    with op.batch_alter_table('video_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_candidates_youtube_video_id'))
        batch_op.drop_index(batch_op.f('ix_video_candidates_track_id'))

    op.drop_table('video_candidates')
    # ### end Alembic commands ###
